disabled_rules:
 - todo
 - no_space_in_method_call
 - comment_spacing
 - multiple_closures_with_trailing_closure
 - redundant_string_enum_value

line_length:
  warning: 200
  error: 300
  ignores_comments: true
  ignores_urls: true
  ignores_interpolated_strings: true

identifier_name:
  allowed_symbols: "_"
  min_length: 1
  excluded:
    - x
    - y
    - i
    - id
    - db

function_body_length:
  warning: 75
  error: 150

function_parameter_count:
  warning: 6
  error: 8

file_length:
  warning: 900
  error: 1200

type_body_length:
  warning: 450
  error: 550

cyclomatic_complexity:
  warning: 15
  error: 20


reporter: "xcode"
