#!/bin/bash
#
# Generate Swift files from environment variables
#
# Environment variables should follow the pattern:
#   ENV_<FileName>_<PropertyName>=value
#
# Example:
#   ENV_AnalyticsConfig_ga4MeasurementId=G-XXXXXXXXXX
#   ENV_AnalyticsConfig_ga4ApiSecret=your_api_key_here
#
# This generates:
#   <output_dir>/AnalyticsConfig.swift with enum AnalyticsConfig
#
# Usage:
#   generate_env_variables.sh <output_directory>
#

set -e

OUTPUT_DIR="${1:-$CI_PRIMARY_REPOSITORY_PATH}"

if [ -z "$OUTPUT_DIR" ]; then
    echo "Error: Output directory not specified"
    echo "Usage: generate_env_variables.sh <output_directory>"
    exit 1
fi

mkdir -p "$OUTPUT_DIR"

# Get unique file names from ENV_ variables
file_names=$(env | grep '^ENV_' | cut -d= -f1 | sed 's/^ENV_//' | cut -d_ -f1 | sort -u)

if [ -z "$file_names" ]; then
    echo "Warning: No ENV_ environment variables found"
    exit 0
fi

generated_count=0

for file_name in $file_names; do
    output_file="$OUTPUT_DIR/${file_name}.swift"
    echo "Generating $output_file..."

    # Start the Swift file
    cat > "$output_file" << EOF
//
//  ${file_name}.swift
//
//  Auto-generated by CI - DO NOT EDIT
//

import Foundation

enum $file_name {
EOF

    # Find all properties for this file
    env | grep "^ENV_${file_name}_" | while IFS='=' read -r var value; do
        # Extract property name (everything after ENV_<FileName>_)
        property_name="${var#ENV_${file_name}_}"
        echo "    static let $property_name = \"$value\"" >> "$output_file"
    done

    # Close the enum
    echo "}" >> "$output_file"

    ((generated_count++))
done

echo "Generated $generated_count file(s)"
