#!/bin/bash
#
# Generate xcconfig file from environment variables
#
# Environment variables should follow the pattern:
#   ENV_<Namespace>_<PropertyName>=value
#
# Example:
#   ENV_AnalyticsConfig_ga4MeasurementId=G-XXXXXXXXXX
#   ENV_AnalyticsConfig_ga4ApiSecret=your-api-secret
#   ENV_FeatureFlags_enableBeta=true
#
# This generates a single xcconfig file with all properties.
#
# Usage:
#   generate_xcconfig.sh <output_directory> [product_name]
#
#   output_directory: Where to write the xcconfig file
#   product_name:     Name for output file (default: CI_PRODUCT or "App")
#                     Output: <output_dir>/<product_name>Config.xcconfig
#
# Security Warning:
#   Values are stored as plain text. Only use for low-sensitivity
#   configuration like analytics IDs, feature flags, and public endpoints.
#   NOT for payment keys, auth secrets, or database credentials.
#

set -e

OUTPUT_DIR="${1:-$CI_PRIMARY_REPOSITORY_PATH}"
PRODUCT_NAME="${2:-${CI_PRODUCT:-App}}"

if [ -z "$OUTPUT_DIR" ]; then
    echo "Error: Output directory not specified"
    echo "Usage: generate_xcconfig.sh <output_directory> [product_name]"
    exit 1
fi

mkdir -p "$OUTPUT_DIR"

# Check for ENV_ variables
env_vars=$(env | grep '^ENV_' || true)

if [ -z "$env_vars" ]; then
    echo "Warning: No ENV_ environment variables found"
    exit 0
fi

output_file="$OUTPUT_DIR/${PRODUCT_NAME}Config.xcconfig"
echo "Generating $output_file..."

# Start the xcconfig file
cat > "$output_file" << EOF
//
//  ${PRODUCT_NAME}Config.xcconfig
//
//  Auto-generated by CI - DO NOT EDIT
//
//  Access in Info.plist: \$(PROPERTY_NAME)
//  Access in Swift: Bundle.main.infoDictionary?["PropertyName"]
//

EOF

# Process all ENV_ variables
property_count=0
env | grep '^ENV_' | sort | while IFS='=' read -r var value; do
    # Extract property name (everything after ENV_<Namespace>_)
    # ENV_AnalyticsConfig_ga4MeasurementId -> ga4MeasurementId
    property_name=$(echo "$var" | sed 's/^ENV_[^_]*_//')
    echo "$property_name = $value" >> "$output_file"
    ((property_count++)) || true
done

echo "Generated $output_file"

# Create wrapper file for local development (skip in CI)
wrapper_file="$OUTPUT_DIR/${PRODUCT_NAME}.xcconfig"

if [ -z "$CI" ] && [ ! -f "$wrapper_file" ]; then
    echo "Creating wrapper $wrapper_file..."
    cat > "$wrapper_file" << EOF
//
//  ${PRODUCT_NAME}.xcconfig
//
#include? "${PRODUCT_NAME}Config.xcconfig"
EOF
    echo "Created $wrapper_file (add to Xcode project and commit)"
fi
