#!/bin/bash
#
# Generate xcconfig files from environment variables
#
# Environment variables should follow the pattern:
#   ENV_<FileName>_<PropertyName>=value
#
# Example:
#   ENV_AppConfig_GA4_MEASUREMENT_ID=G-XXXXXXXXXX
#   ENV_AppConfig_GA4_API_KEY=your-api-key-here
#
# This generates:
#   <output_dir>/AppConfig.xcconfig with key-value pairs
#
# Usage:
#   generate_xcconfig.sh <output_directory>
#
# Security Warning:
#   Values are stored as plain text. Only use for low-sensitivity
#   configuration like analytics IDs, feature flags, and public endpoints.
#   NOT for payment keys, auth secrets, or database credentials.
#

set -e

OUTPUT_DIR="${1:-$CI_PRIMARY_REPOSITORY_PATH}"

if [ -z "$OUTPUT_DIR" ]; then
    echo "Error: Output directory not specified"
    echo "Usage: generate_xcconfig.sh <output_directory>"
    exit 1
fi

mkdir -p "$OUTPUT_DIR"

# Get unique file names from ENV_ variables
file_names=$(env | grep '^ENV_' | cut -d= -f1 | sed 's/^ENV_//' | cut -d_ -f1 | sort -u)

if [ -z "$file_names" ]; then
    echo "Warning: No ENV_ environment variables found"
    exit 0
fi

generated_count=0

for file_name in $file_names; do
    output_file="$OUTPUT_DIR/${file_name}.xcconfig"
    echo "Generating $output_file..."

    # Start the xcconfig file
    cat > "$output_file" << EOF
//
//  ${file_name}.xcconfig
//
//  Auto-generated by CI - DO NOT EDIT
//
//  Access in Info.plist: \$(PROPERTY_NAME)
//  Access in Swift: Bundle.main.infoDictionary?["PropertyName"]
//

EOF

    # Find all properties for this file
    env | grep "^ENV_${file_name}_" | while IFS='=' read -r var value; do
        # Extract property name (everything after ENV_<FileName>_)
        property_name="${var#ENV_${file_name}_}"
        echo "$property_name = $value" >> "$output_file"
    done

    ((generated_count++))
done

echo "Generated $generated_count xcconfig file(s)"
